title: Three bodies
email: jan.machacek@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://threebodies.tech"
# twitter_username: jekyllrb
github_username:  janm399

# Build settings
#theme: minima
remote_theme: nielsenramon/chalk
plugins:
  - jekyll-feed

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
